services:
  web:
    image: richie31/notify:latest
    container_name: noTify
    env_file:
      - C:/Users/Richie/Desktop/secret_files/email/.env
    ports:
      - "5001:5001"
    networks:
      - my_rasp_network

volumes:
  mysql_ubuntu_rasp_device:
    external: true

networks:
  my_rasp_network:
    external: true
