version: '3.3'

services:
 web:
  build:
   context: .
   dockerfile: Dockerfile
  ports:
  - 5001:5001
  container_name: web

 visualisation:
  build:
   context: .
   dockerfile: plot_app/Dockerfile
  ports:
  - 5002:5002
  container_name: visualisation
