version: '3.3'

services:
 web:
  build:
   context: .
   dockerfile: Dockerfile
  ports:
  - 5001:5001
  container_name: web
  networks: 
    static-network: 
        ipv4_address: 172.20.128.2 
networks: 
  static-network: 
    ipam: 
      config: 
        - subnet: 172.20.0.0/16 
          ip_range: 172.28.5.0/24 

# visualisation:
#  build:
#   context: .
#   dockerfile: plot_app/Dockerfile
#  ports:
#  - 5002:5002
#  container_name: visualisation
